name: Check for Broken Markdown links

on: 
  pull_request:
    branches:
    - master
  schedule:
  # Run every Monday at 00:00
  - cron: "0 0 * * 1"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.mlc_config.json'